services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=db_user
      - MARIADB_DATABASE=magento
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_PASSWORD=db_password
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
  magento:
    build: .
    ports:
      - '80:8080'
    environment:
      - MAGENTO_URL=https:/magento.acme.com/
      - MAGENTO_URL_SECURE=https:/magento.acme.com/
      - ADMIN_URL_PREFIX=manage
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@acme.com
      - DB_HOST=mariadb
      - DB_USER=db_user
      - DB_PASSWORD=db_password
      - DB_NAME=magento
      - ES_HOST=elasticsearch
    #command: sleep infinity
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7.9.3
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local
